### PR TITLE
Ephemeral challenge update

### PR DESCRIPTION
**Pull request by tplooker**
#### Short description of what this resolves:

Updates to the ephemeral challenge implementation.

#### Changes proposed in this pull request:

- Register the service with the extensions pack 
- Change function signatures to have Async suffix
- Added a prepare message method
- Added a send to endpoint method
- Added population of the return information of an ephemeral challenge in the request
- Added fields to identify the challenger

### CODE REVIEW

**Comment by tmarkovski** [comment]
Looks good. One unit test is failing.

**Comment by tplooker** [comment]
@tmarkovski thanks all fixed.

**Comment by tplooker** [comment]
@tmarkovski dont merge I have some other changes I would like to add

**Comment by tplooker** [comment]
@tmarkovski done now.

**Pull request merged**
